name: ✅Format Status Check
run-name: ✅Format Status Check (${{ github.base_ref }} branch)


defaults:
  run:
    shell: pwsh


on:
  pull_request_target:
    branches: [main, preview]


jobs:
  format_status_check:
    name: Format Status Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ vars.DENO_VERSION }}

    - name: Run Lint
      run: deno fmt --check
