name: 🚀Release
run-name: ${{ vars.PROJECT_NAME }} ${{ inputs.release-type }} Release ${{ inputs.dry-run == true && '(Dry Run)' || '' }}


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:
    inputs:
      release-type:
        description: The type of release.  Choose 'Preview' or 'Production'.
        required: true
        type: choice
        options: [Preview, Production]
      dry-run:
        required: false
        description: Dry Run (if true, the release will not be created)
        default: false
        type: boolean


jobs:
  get_version:
    name: Get Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ vars.DENO_VERSION }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        working-directory: ${{ github.workspace }}
        run: |
          $scriptPath = "${{ github.workspace }}/.github/cicd/scripts/get-version.ts";

          deno run -R -W -E "$scriptPath";


  validate_release:
    name: Validate Workflow Inputs
    runs-on: ubuntu-latest
    needs: get_version
    steps:
      - name: Validate Workflow Inputs
        run: |
          $branch = "${{ github.ref }}".TrimStart('refs/heads/');
          $expectedPrevBranch = "${{ vars.PREV_RELEASE_BRANCH }}".Trim();
          $expectedProdBranch = "${{ vars.PROD_RELEASE_BRANCH }}".Trim();

          if ($expectedPrevBranch -eq "") {
            Write-Host "::error::The PREV_RELEASE_BRANCH variable is not set.";
            exit 1;
          }

          if ($expectedProdBranch -eq "") {
            Write-Host "::error::The PROD_RELEASE_BRANCH variable is not set.";
            exit 1;
          }

          if ($branch -ne $expectedPrevBranch -and $branch -ne $expectedProdBranch) {
            Write-Host "::error::Releases are only allowed to be run on '$expectedPrevBranch' or '$expectedProdBranch' branches.";
            exit 0; # TODO: THIS NEEDS TO BE CHANGED TO 1 WHNE FINISHED WITH DEBUGGING
          }

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ vars.DENO_VERSION }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Version Does Not Exist
        env:
          OWNER_NAME: "${{ vars.ORGANIZATION_NAME }}"
          REPO_NAME: "${{ vars.PROJECT_NAME }}"
          VERSION_TYPE: "${{ inputs.release-type }}"
          VERSION: "${{ needs.get_version.outputs.version }}"
          GITHUB_TOKEN: "${{ secrets.CICD_TOKEN }}"
        run: |
          $scriptPath = "${{ github.workspace }}/.github/cicd/scripts/version-checker.ts";

          deno run `
          -E `
          -N `
          --allow-run "$scriptPath";

      - name: Release Notes Exist
        env:
          RELEASE_TYPE: "${{ inputs.release-type }}"
          VERSION: "${{ needs.get_version.outputs.version }}"
        run: |
          $scriptPath = "${{ github.workspace }}/.github/cicd/scripts/check-release-notes.ts";

          deno run -E -R "$scriptPath";


  release:
    name: Run ${{ inputs.release-type }} Release
    runs-on: ubuntu-latest
    needs: [get_version, validate_release]
    steps:
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ vars.DENO_VERSION }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Check
        run: deno check **/*/*.ts;

      - name: Run Lint
        run: deno lint

      - name: Run Tests
        run: deno test -R ./tests/*Tests.ts;

      - name: Create GitHub Release ${{ inputs.dry-run == true && '(Dry Run)' || '' }}
        if: ${{ inputs.dry-run == false }}
        env:
          GH_TOKEN: ${{ secrets.CICD_TOKEN }}
        run: |
          $ownerRepoName = "${{ github.repository }}";

          $tag = "${{ needs.get_version.outputs.version }}".ToLower().Trim();
          $tag = $tag.StartsWith("v") ? $tag : "v$tag";

          $releaseType = "${{ inputs.release-type }}";
          $version = "${{ needs.get_version.outputs.version }}";

          $title = "$releaseType Release - $version";

          $releaseDirPrefix = $releaseType.ToLower();
          $releaseTypeDir = "$releaseDirPrefix-releases";
          $fullReleaseNotesPath = "${{ github.workspace }}/release-notes/$releaseTypeDir/Release-Notes-${{ needs.get_version.outputs.version }}.md";

          $isPreRelease = $releaseType -eq "Preview" ? "--prerelease" : "";

          Write-Host "::notice::Release Notes File Path: $fullReleaseNotesPath";

          gh release create $tag `
            -R $ownerRepoName `
            --target ${{ github.ref_name }} `
            -t $title `
            -F $fullReleaseNotesPath `
            $isPreRelease `
            $fullReleaseNotesPath;

      - name: Close Milestone ${{ needs.get_version.outputs.version }}
        if: ${{ inputs.dry-run == false }}
        run: |
          $scriptUrl = "${{ vars.SCRIPT_BASE_URL }}/${{ vars.CICD_SCRIPTS_VERSION }}/${{ vars.SCRIPT_RELATIVE_DIR_PATH }}";
          $scriptUrl = $scriptUrl.Replace("\", "/").Replace("//", "/");
          $scriptUrl = $scriptUrl.EndsWith("/") ? $scriptUrl.Substring(0, $scriptUrl.Length - 1) : $scriptUrl;
          $scriptUrl = "$scriptUrl/close-milestone.ts";

          Write-Host "::notice::Close milestone script URL: $scriptUrl";

          <# Deno Args:
            1. Project name
            2. Milestone name - This is the version
            3. PAT
          #>
          deno run `
            -R `
            -N `
            "$scriptUrl" `
            "${{ vars.PROJECT_NAME }}" `
            "${{ needs.get_version.outputs.version }}" `
            "${{ secrets.CICD_TOKEN }}";
